### ISSUE TITLE
script fails unhelpfully

### ISSUE THREAD

**Issue by DennisHeimbigner** [github/ssh-key-algo#10]
When I do this:
>  ./ssh-key-algo.sh 

I get
> using: /usr/bin/ssh
>Could not authenticate to git@github.com, and could not understand your key type because of that.

What does this mean?

**Comment by tgummerer** [comment]
The script only works if your ssh key is set up to authenticate to `github.com` (or any other place that you can pass in as `<user>@<hostname>`).  So this means your ssh key is not set up on github.com, and thus the script can not detect the key type.

**Comment by leo-dosu** [comment]
> The script only works if your ssh key is set up to authenticate to `github.com` (or any other place that you can pass in as `<user>@<hostname>`). So this means your ssh key is not set up on github.com, and thus the script can not detect the key type.

@tgummerer  i want to presume that to be the intent of the script, it basically confirms that the  new ssh requirement, and if not it gives an error

**Comment by tgummerer** [comment]
Yes, it also gives some suggestions on what can be done to set up the key properly based on OpenSSH versions etc.

Since the original reporter hasn't responded in a long time, I'm gonna close this issue out.
