### ISSUE TITLE
script report 'You're all set!' but I cannot clone

### ISSUE THREAD

**Issue by jano2358** [github/ssh-key-algo#15]
I just added a ssh key to my profile as instructed in https://docs.github.com/en/authentication/connecting-to-github-with-ssh
authentication with ssh -T git@github.com is successful
then I run the script:
jano@cata  ~  /usr/bin/sh ./ssh-key-algo git@github.com           
using: /usr/bin/ssh
You're using an Ed25519 key.  You're all set!

then I try to clone something:

 jano@cata  ~  git clone git://github.com/DreamSourceLab/DSView.git
Cloning into 'DSView'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

I cannot clone, is the script lying or am I doing something wrong?

**Comment by tgummerer** [comment]
> git clone git://github.com/DreamSourceLab/DSView.git

This is trying to use the `git://` protocol we deprecated.  You can use the ssh protocol instead, using `git clone git@github.com:DreamSourceLab/DSView.git`, which should be working with the ssh key you set up.

**Comment by jano2358** [comment]
Ok, all clear now. @ instead of :// , I probably didn't read that. Thanks!
